name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    concurrency:
      group: main
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ref: generated
          path: './out/generated'

      - uses: actions/checkout@v3
        with:
          ref: locales
          path: './out/locales'

      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - run: npx @spyglassmc/mcdoc-cli locale ./out/locales/en.json --upgrade --verbose

      - run: npx @spyglassmc/mcdoc-cli export ./out/generated/symbols.json --ref --verbose

      - uses: EndBug/add-and-commit@v9
        with:
          cwd: './out/generated'
          author_name: GitHub Actions
          author_email: actions@github.com
          message: '🚀 Update exported symbols'

      - uses: EndBug/add-and-commit@v9
        with:
          cwd: './out/locales'
          author_name: 'GitHub Actions'
          author_email: actions@github.com
          message: '🌐 Update localization'
